# Generated by Django 6.0.6 on 2026-06-27 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Mert Orhan', max_length=120, verbose_name='Ad Soyad')),
                ('role', models.CharField(blank=True, default='', max_length=160, verbose_name='Unvan')),
                ('tagline', models.CharField(blank=True, default='', max_length=200, verbose_name='Ana sayfa sloganı')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Profil fotoğrafı')),
                ('about_title', models.CharField(blank=True, default='', max_length=200, verbose_name='Hakkında başlığı')),
                ('bio', models.TextField(blank=True, default='', verbose_name='Biyografi')),
                ('linkedin_url', models.URLField(blank=True, default='', verbose_name='LinkedIn adresi')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-posta')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/', verbose_name='CV (PDF)')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profil',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Sıra')),
                ('date_range', models.CharField(max_length=80, verbose_name='Tarih aralığı')),
                ('role', models.CharField(max_length=200, verbose_name='Pozisyon · Şirket')),
                ('description', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='core.profile', verbose_name='Profil')),
            ],
            options={
                'verbose_name': 'Deneyim',
                'verbose_name_plural': 'Deneyimler',
                'ordering': ['order'],
            },
        ),
    ]
