# Generated by Django 6.0.6 on 2026-07-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instagram_url',
            field=models.URLField(blank=True, default='', verbose_name='Instagram adresi'),
        ),
    ]
