# Generated by Django 6.0.6 on 2026-09-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_instagram_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kriter')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='Açıklama')),
                ('order', models.PositiveIntegerField(default=10, verbose_name='Sıra')),
                ('for_movies', models.BooleanField(default=True, verbose_name="Film & Dizi'de kullanılsın")),
                ('for_books', models.BooleanField(default=False, verbose_name='Kitaplarda kullanılsın')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Puan Kriteri',
                'verbose_name_plural': 'Puan Kriterleri',
                'ordering': ['order', 'name'],
            },
        ),
    ]
