# Generated by Django 6.0.6 on 2026-06-27 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('slug', models.SlugField(blank=True, max_length=80, null=True, unique=True, verbose_name='Adres (slug)')),
                ('entry_type', models.CharField(choices=[('mekan', 'Tek Mekan'), ('rota', 'Çok Duraklı Rota')], default='rota', max_length=10, verbose_name='Tür')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='guide/', verbose_name='Kapak görseli')),
                ('highlight', models.CharField(blank=True, default='', max_length=200, verbose_name='Vurucu cümle (hero)')),
                ('summary', models.TextField(blank=True, default='', verbose_name='Kart özeti')),
                ('overview', models.TextField(blank=True, default='', verbose_name='Genel bakış / editör notu')),
                ('city', models.CharField(blank=True, default='', max_length=80, verbose_name='Şehir')),
                ('budget', models.CharField(blank=True, choices=[('₺', '₺ — Ekonomik'), ('₺₺', '₺₺ — Orta'), ('₺₺₺', '₺₺₺ — Yüksek')], default='', max_length=6, verbose_name='Bütçe')),
                ('best_time', models.CharField(blank=True, choices=[('ilkbahar', 'İlkbahar'), ('yaz', 'Yaz'), ('sonbahar', 'Sonbahar'), ('kis', 'Kış'), ('tum-yil', 'Tüm Yıl')], default='', max_length=20, verbose_name='En iyi zaman')),
                ('suitable_for', models.CharField(blank=True, choices=[('cift', 'Çiftler'), ('aile', 'Ailecek'), ('solo', 'Tek Başına'), ('arkadas', 'Arkadaş Grubu'), ('herkes', 'Herkese Uygun')], default='', max_length=20, verbose_name='Kime uygun')),
                ('duration', models.CharField(blank=True, default='', max_length=50, verbose_name='Süre')),
                ('verdict', models.TextField(blank=True, default='', verbose_name='Dürüst değerlendirme')),
                ('practical_info', models.TextField(blank=True, default='', verbose_name='Pratik bilgi')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne çıkan')),
                ('is_published', models.BooleanField(default=True, verbose_name='Yayında')),
                ('published_at', models.DateField(auto_now_add=True, verbose_name='Yayın tarihi')),
            ],
            options={
                'verbose_name': 'Gezi / Öneri',
                'verbose_name_plural': 'Gezi / Öneriler',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='GuideStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Sıra')),
                ('name', models.CharField(max_length=200, verbose_name='Durak adı')),
                ('point_type', models.CharField(choices=[('gezilecek', 'Gezilecek Yer'), ('yeme-icme', 'Yeme-İçme'), ('ogrenme', 'Öğrenme'), ('konaklama', 'Konaklama')], default='gezilecek', max_length=12, verbose_name='Durak türü')),
                ('description', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('hours', models.CharField(blank=True, default='', max_length=80, verbose_name='Önerilen saat')),
                ('cost', models.CharField(blank=True, default='', max_length=80, verbose_name='Yaklaşık ücret')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='guide.guide', verbose_name='Bağlı gezi')),
            ],
            options={
                'verbose_name': 'Gezi Durağı',
                'verbose_name_plural': 'Gezi Durakları',
                'ordering': ['order'],
            },
        ),
    ]
