# Generated by Django 6.0.6 on 2026-07-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidestop',
            name='point_type',
            field=models.CharField(choices=[('gezilecek', 'Gezilecek Yer'), ('yeme-icme', 'Yeme-İçme'), ('ogrenme', 'Öğrenme'), ('konaklama', 'Konaklama'), ('deneyim', 'Deneyim')], default='gezilecek', max_length=12, verbose_name='Durak türü'),
        ),
    ]
