# Generated by Django 6.0.6 on 2026-07-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_alter_guidestop_point_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Enlem'),
        ),
        migrations.AddField(
            model_name='guide',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Boylam'),
        ),
        migrations.AddField(
            model_name='guidestop',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Enlem'),
        ),
        migrations.AddField(
            model_name='guidestop',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Boylam'),
        ),
    ]
