# Generated by Django 6.0.6 on 2026-09-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_guide_latitude_guide_longitude_guidestop_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='is_hero',
            field=models.BooleanField(default=False, verbose_name='Ana sayfa vitrininde göster'),
        ),
    ]
