# Generated by Django 6.0.6 on 2026-06-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Fotoğraf')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('category', models.CharField(blank=True, choices=[('Manzara', 'Manzara'), ('Sokak', 'Sokak'), ('Portre', 'Portre')], default='', max_length=20, verbose_name='Kategori')),
                ('location', models.CharField(blank=True, default='', max_length=120, verbose_name='Konum')),
                ('taken_at', models.DateField(blank=True, null=True, verbose_name='Çekim tarihi')),
                ('camera', models.CharField(blank=True, default='', max_length=100, verbose_name='Kamera')),
                ('lens', models.CharField(blank=True, default='', max_length=100, verbose_name='Lens')),
                ('iso', models.CharField(blank=True, default='', max_length=20, verbose_name='ISO')),
                ('shutter_speed', models.CharField(blank=True, default='', max_length=20, verbose_name='Enstantane')),
                ('aperture', models.CharField(blank=True, default='', max_length=20, verbose_name='Diyafram')),
                ('focal_length', models.CharField(blank=True, default='', max_length=20, verbose_name='Odak')),
                ('is_published', models.BooleanField(default=True, verbose_name='Yayında')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Eklenme tarihi')),
            ],
            options={
                'verbose_name': 'Fotoğraf',
                'verbose_name_plural': 'Fotoğraflar',
                'ordering': ['-created_at'],
            },
        ),
    ]
