# Generated by Django 6.0.6 on 2026-09-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_photo_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
