# Generated by Django 6.0.6 on 2026-09-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_photo_image_height_photo_image_width'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Fotoğraf', 'verbose_name_plural': 'Fotoğraflar'},
        ),
        migrations.AddField(
            model_name='photo',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sıra'),
        ),
    ]
