# Generated by Django 6.0.6 on 2026-09-05 10:28
#
# ELLE DUZENLENDI. Otomatik uretilen hâli tek bir AlterField'di: metin
# sutununu dogrudan FK'ye cevirmeye calisiyor, yani "Manzara" yazan
# kategoriler sessizce yok oluyordu. Bunun yerine besli sira:
#
#   1. Kategori tablosunu kur
#   2. Yeni FK sutununu YANINA ekle
#   3. Eski metinleri okuyup yeni sutuna bagla   <- veri burada tasiniyor
#   4. Eski metin sutununu kaldir
#   5. Yeni sutunu "category" adina tasi
#
# Sira onemli: veri tasima adimi, iki sutunun da var oldugu tek an.

import django.db.models.deletion
from django.db import migrations, models


# Mevcut secenekler ve sira degerleri. Listede olmayan bir kategori
# cikarsa (elle girilmis eski bir deger) 40'tan itibaren onluk devam eder.
BILINEN_SIRA = {
    "Manzara": 10,
    "Sokak": 20,
    "Portre": 30,
}


def kategorileri_tasi(apps, schema_editor):
    """Her fotografin metin kategorisini karsilik gelen kayda baglar."""
    Photo = apps.get_model("gallery", "Photo")
    PhotoCategory = apps.get_model("gallery", "PhotoCategory")

    sonraki_sira = 40

    for foto in Photo.objects.exclude(category="").exclude(category=None):
        ad = foto.category.strip()
        if not ad:
            continue

        kayit = PhotoCategory.objects.filter(name=ad).first()
        if kayit is None:
            if ad in BILINEN_SIRA:
                sira = BILINEN_SIRA[ad]
            else:
                sira = sonraki_sira
                sonraki_sira += 10
            kayit = PhotoCategory.objects.create(name=ad, order=sira)

        # Kategorisi bos olan fotograf bos kalir: dongu zaten onlari almiyor.
        Photo.objects.filter(pk=foto.pk).update(category_yeni=kayit)


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_photo_options_photo_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Ad')),
                ('order', models.PositiveIntegerField(default=10, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Fotoğraf Kategorisi',
                'verbose_name_plural': 'Fotoğraf Kategorileri',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='category_yeni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.photocategory', verbose_name='Kategori'),
        ),
        # Geri sarilabilir ama veri GERI GELMEZ: eski metin sutunu silindigi
        # icin geri donuste kategoriler bos kalir. noop bilincli.
        migrations.RunPython(kategorileri_tasi, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='photo',
            name='category',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='category_yeni',
            new_name='category',
        ),
    ]
