# Generated by Django 6.0.6 on 2026-07-06 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kitap adı')),
                ('slug', models.SlugField(blank=True, max_length=80, null=True, unique=True, verbose_name='Adres (slug)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/', verbose_name='Kapak')),
                ('author', models.CharField(max_length=200, verbose_name='Yazar')),
                ('translator', models.CharField(blank=True, default='', max_length=200, verbose_name='Çevirmen')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, verbose_name='Puanım (1-10)')),
                ('summary', models.TextField(blank=True, default='', verbose_name='Kart özeti')),
                ('body', models.TextField(verbose_name='Özet / Eleştiri')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne çıkan')),
                ('is_published', models.BooleanField(default=True, verbose_name='Yayında')),
                ('published_at', models.DateField(auto_now_add=True, verbose_name='Yayın tarihi')),
            ],
            options={
                'verbose_name': 'Kitap',
                'verbose_name_plural': 'Kitaplar',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='BookQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Sıra')),
                ('text', models.TextField(verbose_name='Alıntı')),
                ('page', models.CharField(blank=True, default='', max_length=20, verbose_name='Sayfa (ops.)')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='books.book', verbose_name='Kitap')),
            ],
            options={
                'verbose_name': 'Alıntı',
                'verbose_name_plural': 'Alıntılar',
                'ordering': ['order'],
            },
        ),
    ]
