# Generated by Django 6.0.6 on 2026-09-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_hero',
            field=models.BooleanField(default=False, verbose_name='Ana sayfa vitrininde göster'),
        ),
    ]
