# Generated by Django 6.0.6 on 2026-09-02 10:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def eski_puanlari_temizle(apps, schema_editor):
    """
    Mevcut puanlari NULL yapar.

    Eski puanlar elle girilmisti, arkalarinda kriter yok — yeni sistemde
    "ortalama" olarak gosterilirlerse yalan soylemis oluruz. Alan artik
    admin'de salt okunur oldugu icin elle de temizlenemiyor; bu yuzden
    temizlik migration'a birakildi. (movies 0003'un esi.)
    """
    apps.get_model("books", "Book").objects.update(rating=None)


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_is_hero'),
        ('core', '0004_ratingcriterion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Ortalama puan (otomatik)'),
        ),
        # Geri alinamaz: puanlar siliniyor, geri donuste uretilecek bir
        # kaynak yok. noop, migration'in geri sarilabilmesi icin.
        migrations.RunPython(eski_puanlari_temizle, migrations.RunPython.noop),
        migrations.CreateModel(
            name='BookScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Puan (1-10)')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='books.book', verbose_name='Kitap')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ratingcriterion', verbose_name='Kriter')),
            ],
            options={
                'verbose_name': 'Kriter Puanı',
                'verbose_name_plural': 'Kriter Puanları',
                'ordering': ['criterion__order'],
                'constraints': [models.UniqueConstraint(fields=('book', 'criterion'), name='unique_book_criterion')],
            },
        ),
    ]
