# Generated by Django 6.0.6 on 2026-09-07 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_rating_bookscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Yazar',
                'verbose_name_plural': 'Yazarlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Kitap türü',
                'verbose_name_plural': 'Kitap türleri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Yayınevi',
                'verbose_name_plural': 'Yayınevleri',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='read_at',
            field=models.DateField(blank=True, null=True, verbose_name='Okuma tarihi'),
        ),
        migrations.AddField(
            model_name='book',
            name='release_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Basım yılı'),
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, to='books.author', verbose_name='Yazarlar'),
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, to='books.genre', verbose_name='Türler'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='books.publisher', verbose_name='Yayınevi'),
        ),
    ]
