# Generated by Django 6.0.6 on 2026-09-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_author_genre_publisher_book_read_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Çevirmen',
                'verbose_name_plural': 'Çevirmenler',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='translators',
            field=models.ManyToManyField(blank=True, to='books.translator', verbose_name='Çevirmenler'),
        ),
    ]
