# Generated by Django 6.0.6 on 2026-06-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_alter_blogpost_options_blogpost_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='pullquote',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Vurgulu alıntı'),
        ),
    ]
