# Generated by Django 6.0.6 on 2026-07-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='pullquote',
            field=models.TextField(blank=True, default='', verbose_name='Vurgulu alıntı'),
        ),
    ]
