# Generated by Django 6.0.6 on 2026-08-25 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_pullquote'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('kind', models.CharField(choices=[('paragraph', 'Paragraf'), ('heading', 'Başlık'), ('image', 'Görsel'), ('quote', 'Alıntı'), ('embed', 'Gömü')], default='paragraph', max_length=20, verbose_name='Blok türü')),
                ('text', models.TextField(blank=True, default='', verbose_name='Metin')),
                ('heading_level', models.CharField(blank=True, choices=[('h2', 'Ana başlık'), ('h3', 'Alt başlık')], default='', max_length=2, verbose_name='Başlık düzeyi')),
                ('in_toc', models.BooleanField(default=False, verbose_name='İçindekiler listesinde göster')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/sections/', verbose_name='Görsel')),
                ('image_title', models.CharField(blank=True, default='', max_length=200, verbose_name='Görsel başlığı (üstte)')),
                ('image_caption', models.CharField(blank=True, default='', max_length=300, verbose_name='Görsel etiketi (altta)')),
                ('image_alt', models.CharField(blank=True, default='', max_length=200, verbose_name='Alt metin (erişilebilirlik)')),
                ('quote_source', models.CharField(blank=True, default='', max_length=200, verbose_name='Alıntının kaynağı')),
                ('embed_url', models.URLField(blank=True, default='', verbose_name='Gömü bağlantısı')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='blog.blogpost', verbose_name='Bağlı yazı')),
            ],
            options={
                'verbose_name': 'Bölüm',
                'verbose_name_plural': 'Bölümler',
                'ordering': ['order', 'id'],
            },
        ),
    ]
