# Generated by Django 6.0.6 on 2026-08-25 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='published_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Yayın tarihi'),
        ),
    ]
