# Generated by Django 6.0.6 on 2026-09-01 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpost_published_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='reading_time',
        ),
    ]
