# Generated by Django 6.0.6 on 2026-09-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_blogpost_reading_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsection',
            name='in_toc',
            field=models.BooleanField(default=True, verbose_name='İçindekiler listesinde göster'),
        ),
    ]
