# Generated by Django 6.0.6 on 2026-07-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Ad')),
                ('slug', models.SlugField(blank=True, max_length=80, null=True, unique=True, verbose_name='Adres (slug)')),
                ('content_type', models.CharField(choices=[('film', 'Film'), ('dizi', 'Dizi')], default='film', max_length=5, verbose_name='Tür')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='movies/', verbose_name='Kapak / Afiş')),
                ('director', models.CharField(blank=True, default='', max_length=200, verbose_name='Yönetmen')),
                ('screenwriter', models.CharField(blank=True, default='', max_length=200, verbose_name='Senarist')),
                ('lead_actors', models.CharField(blank=True, default='', max_length=300, verbose_name='Başrol oyuncuları')),
                ('release_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yapım yılı')),
                ('genre', models.CharField(blank=True, default='', max_length=100, verbose_name='Tarz (örn: Bilim Kurgu)')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, verbose_name='Puanım (1-10)')),
                ('summary', models.TextField(blank=True, default='', verbose_name='Kart özeti')),
                ('body', models.TextField(verbose_name='Yorum / İnceleme')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne çıkan')),
                ('is_published', models.BooleanField(default=True, verbose_name='Yayında')),
                ('published_at', models.DateField(auto_now_add=True, verbose_name='Yayın tarihi')),
            ],
            options={
                'verbose_name': 'Film / Dizi İncelemesi',
                'verbose_name_plural': 'Film / Dizi İncelemeleri',
                'ordering': ['-published_at'],
            },
        ),
    ]
