# Generated by Django 6.0.6 on 2026-09-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_review_rating_reviewscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Oyuncu',
                'verbose_name_plural': 'Oyuncular',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Yönetmen',
                'verbose_name_plural': 'Yönetmenler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Tür',
                'verbose_name_plural': 'Türler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Screenwriter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Senarist',
                'verbose_name_plural': 'Senaristler',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='review',
            name='watched_at',
            field=models.DateField(blank=True, null=True, verbose_name='İzleme tarihi'),
        ),
        migrations.AddField(
            model_name='review',
            name='actors',
            field=models.ManyToManyField(blank=True, to='movies.actor', verbose_name='Oyuncular'),
        ),
        migrations.AddField(
            model_name='review',
            name='directors',
            field=models.ManyToManyField(blank=True, to='movies.director', verbose_name='Yönetmenler'),
        ),
        migrations.AddField(
            model_name='review',
            name='genres',
            field=models.ManyToManyField(blank=True, to='movies.genre', verbose_name='Türler'),
        ),
        migrations.AddField(
            model_name='review',
            name='screenwriters',
            field=models.ManyToManyField(blank=True, to='movies.screenwriter', verbose_name='Senaristler'),
        ),
    ]
