# Generated by Django 6.0.6 on 2026-09-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_actor_director_genre_screenwriter_review_watched_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='runtime',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Süre (dakika)'),
        ),
    ]
